global:
  scrape_interval: 15s # selang waktu dalam menjalankan proses pengumpulan.
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"
 
 
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s 
    metrics_path: /monitoring/prometheus/metrics # metrik endpoint dari TensorFlow Serving
    static_configs:
      - targets: ['emotion-nlp-model-production.up.railway.app'] # alamat dari TensorFlow Serving